// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideojuegosAPI.Models;

#nullable disable

namespace VideojuegosAPI.Migrations
{
    [DbContext(typeof(BdVideojuegosContext))]
    partial class BdVideojuegosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideojuegosAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Categorias");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Juegos de aventura",
                            Nombre = "Aventura"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Juegos de deportes",
                            Nombre = "Deportes"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Juegos de estrategia",
                            Nombre = "Estrategia"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Juegos de rol",
                            Nombre = "Rol"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Juegos de shooter",
                            Nombre = "Shooter"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Juegos de simulacion",
                            Nombre = "Simulacion"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Juegos de survival",
                            Nombre = "Survival"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Juegos de plataformas",
                            Nombre = "Plataformas"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Juegos de puzzle",
                            Nombre = "Puzzle"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Juegos musicales",
                            Nombre = "Musical"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Juegos de carreras",
                            Nombre = "Carreras"
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Juegos de lucha",
                            Nombre = "Lucha"
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Juegos MMORPG",
                            Nombre = "MMORPG"
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Juegos MOBA",
                            Nombre = "MOBA"
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Juegos Battle Royale",
                            Nombre = "Battle Royale"
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Juegos de terror",
                            Nombre = "Terror"
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Juegos de ciencia ficcion",
                            Nombre = "Ciencia Ficcion"
                        },
                        new
                        {
                            Id = 18,
                            Descripcion = "Juegos de fantasia",
                            Nombre = "Fantasia"
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Juegos historicos",
                            Nombre = "Historico"
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Juegos de mundo abierto",
                            Nombre = "Mundo Abierto"
                        },
                        new
                        {
                            Id = 21,
                            Descripcion = "Juegos indie",
                            Nombre = "Indie"
                        },
                        new
                        {
                            Id = 22,
                            Descripcion = "Juegos retro",
                            Nombre = "Retro"
                        },
                        new
                        {
                            Id = 23,
                            Descripcion = "Juegos de realidad virtual",
                            Nombre = "Realidad Virtual"
                        },
                        new
                        {
                            Id = 24,
                            Descripcion = "Juegos de realidad aumentada",
                            Nombre = "Realidad Aumentada"
                        },
                        new
                        {
                            Id = 25,
                            Descripcion = "Juegos cooperativos",
                            Nombre = "Cooperativo"
                        },
                        new
                        {
                            Id = 26,
                            Descripcion = "Juegos competitivos",
                            Nombre = "Competitivo"
                        },
                        new
                        {
                            Id = 27,
                            Descripcion = "Juegos multijugador",
                            Nombre = "Multijugador"
                        });
                });

            modelBuilder.Entity("VideojuegosAPI.Models.Videojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("Anio");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Desarrollador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Imagen")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Precio")
                        .HasColumnType("float")
                        .HasColumnName("Precio");

                    b.HasKey("Id")
                        .HasName("PK_Videojuegos");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Videojuegos", (string)null);
                });

            modelBuilder.Entity("VideojuegosAPI.Models.Videojuego", b =>
                {
                    b.HasOne("VideojuegosAPI.Models.Categoria", "Categoria")
                        .WithMany("Videojuegos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Videojuegos_Categorias");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("VideojuegosAPI.Models.Categoria", b =>
                {
                    b.Navigation("Videojuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
